### ISSUE TITLE
[feature]OPENAI_API_BASE support

### ISSUE THREAD

**Issue by VectorZhao** [reply2future/xExtension-NewsAssistant#20]
Please add support for a third-party BASE URL. Allow users to customize the base URL at their discretion.

**Comment by VectorZhao** [comment]
Yes, just like the `https://api.openai.com`, same structure with openai.

I am using the [one-api](https://github.com/songquanpeng/one-api).

**Comment by reply2future** [comment]
you could try [this new version](https://github.com/reply2future/xExtension-NewsAssistant/releases/tag/v0.9).

**Comment by VectorZhao** [comment]
Not work for me.

<img width="761" alt="image" src="https://github.com/reply2future/xExtension-NewsAssistant/assets/16644993/5bc996fc-2b28-4a6b-98e9-73f9bc0554ae">
<img width="700" alt="image" src="https://github.com/reply2future/xExtension-NewsAssistant/assets/16644993/e9ed1a6f-74f5-4c01-9ba7-e6dde35cedf1">

**Comment by VectorZhao** [comment]
![image](https://github.com/reply2future/xExtension-NewsAssistant/assets/16644993/2d49b92d-92f6-4927-a8c9-b8fc33856a21)

**Comment by reply2future** [comment]
I fixed the bug and passed the test with `one-api` using the [v0.10](https://github.com/reply2future/xExtension-NewsAssistant/releases/tag/v0.10)

**Comment by VectorZhao** [comment]
Cheers, worked!

I have a few suggestions:
1. Present the summary content in a list format. Can you make the summary content in the form of a list to enhance readability? I added "summary the contents in bullet points" in the prompt, but it didn't work.
2. Include hyperlinks within the summary content to facilitate navigation to desired entries.
3. I am unsure if it is feasible to implement scheduled summarization and subsequently push the summarized content to a Telegram bot.

**Comment by VectorZhao** [comment]
I believe another highly beneficial feature would be the ability for ChatGPT to compile the desired content into a designated folder by means of prompting words. Although FreshRSS may not have the concept of folders, tags can be added instead. For instance, ChatGPT could read the titles and contents of the subscribed feed and identify whether a particular subscription is relevant to machine learning. If it is, a tag of "machine learning" could be added.

**Comment by reply2future** [comment]
> Cheers, worked!
> 
> I have a few suggestions:
> 
> 1. Present the summary content in a list format. Can you make the summary content in the form of a list to enhance readability? I added "summary the contents in bullet points" in the prompt, but it didn't work.
> 2. Include hyperlinks within the summary content to facilitate navigation to desired entries.
> 3. I am unsure if it is feasible to implement scheduled summarization and subsequently push the summarized content to a Telegram bot.

1. [This version fixed it](https://github.com/reply2future/xExtension-NewsAssistant/releases/tag/v0.11)
2. Create a new issue to track it #30 
3. Create a new issue to track it #31 

Thanks for your great idea.

**Comment by reply2future** [comment]
> I believe another highly beneficial feature would be the ability for ChatGPT to compile the desired content into a designated folder by means of prompting words. Although FreshRSS may not have the concept of folders, tags can be added instead. For instance, ChatGPT could read the titles and contents of the subscribed feed and identify whether a particular subscription is relevant to machine learning. If it is, a tag of "machine learning" could be added.

Track at #32
