### ISSUE TITLE
Groq AI support

### ISSUE THREAD

**Issue by Whichbfj28** [reply2future/xExtension-NewsAssistant#25]
https://console.groq.com/docs/openai

**Comment by VectorZhao** [comment]
+1

**Comment by reply2future** [comment]
You could use [Portkey-AI/gateway](https://github.com/Portkey-AI/gateway/) to solve it. More details you could find from [this release](https://github.com/reply2future/xExtension-NewsAssistant/releases/tag/v0.11).
