### ISSUE TITLE
Can Markdown be used for rendering during the final output. Easy to read

### ISSUE THREAD

**Issue by Whichbfj28** [reply2future/xExtension-NewsAssistant#26]
Can Markdown be used for rendering during the final output. Easy to read

**Comment by reply2future** [comment]
It should be like this:
<img width="1429" alt="image" src="https://github.com/reply2future/xExtension-NewsAssistant/assets/6359152/d3587ab9-41c6-4702-a1e0-845636695892">

Appreciate to AI to teach me how to write this code :). Welcome any suggestions.
