### ISSUE TITLE
Ollama Support?

### ISSUE THREAD

**Issue by Leopere** [reply2future/xExtension-NewsAssistant#37]
This is wonderful but I don't want to spend thousands of dollars a month to get the results from this stuff Ollama is probably more than enough.

**Comment by reply2future** [comment]
Yes, it did. You could config like this:
<img width="705" alt="image" src="https://github.com/reply2future/xExtension-NewsAssistant/assets/6359152/9857e6ee-0966-4a97-a7c5-25d9328ecaf4">

**Comment by Leopere** [comment]
blessed be I searched the readme and the issues and saw no mention of ollama <3 awesome work!

**Comment by Leopere** [comment]
It does look like it's only a partial Open AI key but you should consider burning the key if thats yours.

**Comment by reply2future** [comment]
> It does look like it's only a partial Open AI key but you should consider burning the key if thats yours.

Thank you for reminding me. :)
