### ISSUE TITLE
Cannot get this to work..any help is appreciated...

### ISSUE THREAD

**Issue by pfuller88** [reply2future/xExtension-NewsAssistant#38]
I tried many times.  I put in my openai api key  sk-proj-H2hWKyBlRKQ......   and have the extension enabled , version ...News Assistant (0.11.1).    I notice in the web config, the drop down boxes don't have any options outside the 1 default, -- openai and gpt-3.5-turbo-16k-0613.    When i click the news assistant button (which seems to be greyed out), it just gives me the page that shows...

The summary of Today
Read ← Go back

with no api data.   

The log file stated it could not find the parameters in the config file.   I looked at the main freshrss config files and found these entries

  'extensions_enabled' => 
  array (
    'News Assistant' => true,
  ),
  'openai_base_url' => 'https://api.openai.com',
  'openai_api_key' => 'sk-proj-H2hWKyBl.......................................',
  'provider' => 'openai',
  'max_tokens' => 4096,
  'temperature' => 0.7,
  'limit' => 10.0,
  'model' => 'gpt-3.5-turbo-16k-0613',
  'prompt' => 'Summarize this as you are news editor, you should merge the similar topic.',
  'field' => 'content',
);

**Comment by reply2future** [comment]
There are two steps you could do:
1. You could follow this steps https://github.com/reply2future/xExtension-NewsAssistant/issues/16#issuecomment-1722202429 to see the logs.
2. Open the development tool on the page `The summary of Today`, could you see the websocket request? Or is there any error message?

**Comment by pfuller88** [comment]
This seems to be the relavent log entry ...
[Thu Jun 13 10:05:53.430510 2024] [proxy_fcgi:error] [pid 963:tid 135433860155072] [remote 184.145.12.171:40817] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: FreshRSS_EntryDAO::listWhere(): Argument #6 ($offset) must be of type int, string given, called in /var/www/FreshRSS/extensions/xExtension-NewsAssistant-main/Controllers/assistantController.php on line 118 and defined in /var/www/FreshRSS/app/Models/EntryDAO.php:1193\nStack trace:\n#0 /var/www/FreshRSS/extensions/xExtension-NewsAssistant-main/Controllers/assistantController.php(118): FreshRSS_EntryDAO->listWhere()\n#1 /var/www/FreshRSS/extensions/xExtension-NewsAssistant-main/Controllers/assistantController.php(74): FreshExtension_assistant_Controller->getNews()\n#2 /var/www/FreshRSS/lib/Minz/Dispatcher.php(120): FreshExtension_assistant_Controller->streamAction()\n#3 /var/www/FreshRSS/lib/Minz/Dispatcher.php(49): Minz_Dispatcher->launchAction()\n#4 /var/www/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()\n#5 /var/www/FreshRSS/p/i/index.php(59): Minz_FrontController->run()\n#6 {main}\n  thrown in /var/www/FreshRSS/app/Models/EntryDAO.php ...'

**Comment by reply2future** [comment]
It was fixed by `v0.11.2`. If there are any problems, open this issue. :)

**Comment by pfuller88** [comment]
thanks, I will try shortly and comment back

**Comment by pfuller88** [comment]
Working now, thanks.

**Comment by pfuller88** [comment]
Here's a tip, try this as your prompt...

Summarize this into bulletpoints as you are news editor. You should merge similar topics.  Please select a fitting emoji for each bulletpoint.

**Comment by pfuller88** [comment]
One more note for you.  I put the latest openai "gpt-4o" into the model input in your extension (without the quotes) and it works fine.  I checked my openai usage and it is indeed using the 4o model.

**Comment by tareefdev** [comment]
I am getting the same issue with 11.2:
````
[Sat May 17 15:01:50.222060 2025] [php:error] [pid 7834:tid 7834] [client 146.70.117.12:0] PHP Fatal error:  Uncaught TypeError: FreshRSS_EntryDAO::listWhere(): Argument #4 ($filters) must be of type ?FreshRSS_BooleanSearch, string given, called in /var/www/FreshRSS/extensions/xExtension-NewsAssistant-0.11.2/Controllers/assistantController.php on line 118 and defined in /var/www/FreshRSS/app/Models/EntryDAO.php:1391\nStack trace:\n#0 /var/www/FreshRSS/extensions/xExtension-NewsAssistant-0.11.2/Controllers/assistantController.php(118): FreshRSS_EntryDAO->listWhere()\n#1 /var/www/FreshRSS/extensions/xExtension-NewsAssistant-0.11.2/Controllers/assistantController.php(74): FreshExtension_assistant_Controller->getNews()\n#2 /var/www/FreshRSS/lib/Minz/Dispatcher.php(117): FreshExtension_assistant_Controller->streamAction()\n#3 /var/www/FreshRSS/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction()\n#4 /var/www/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()\n#5 /var/www/FreshRSS/p/i/index.php(59): Minz_FrontController->run()\n#6 {main}\n  thrown in /var/www/FreshRSS/app/Models/EntryDAO.php on line 1391
````

**Comment by tareefdev** [comment]
I am not sure if FreshRSS recently changed the signature of the function, however using named aurgments solved the issue:

$generator = $this->entryDAO->listWhere(
    type: self::NEWS_CATEGORY_TYPE,
    id: $cat_id,
    state: $state,
    filters: null,
    order: 'DESC',
    limit: $limit
);
